[project]
name = "docuquery-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "aiosqlite>=0.21.0",
    "alembic>=1.17.1",
    "anyio>=4.11.0",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.120.3",
    "httpx>=0.28.1",
    "pgvector>=0.4.1",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-tornasync>=0.6.0.post2",
    "pytest-trio>=0.8.0",
    "pytest-twisted>=1.14.3",
    "python-dotenv>=1.2.1",
    "python-json-logger>=4.0.0",
    "sqlalchemy>=2.0",
    "twisted>=25.5.0",
]
[project.optional-dependencies]
test = [
    "pytest>=8.4.0",
    "pytest-asyncio>=0.24.0",
    "httpx>=0.28.1",
]
[tool.setuptools]
packages = ["app"]
