"""Add cached_queries table for semantic caching new

Revision ID: a0f7ab8486ce
Revises: e40291de16a1
Create Date: 2025-11-10 12:33:50.351956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f7ab8486ce'
down_revision: Union[str, Sequence[str], None] = 'e40291de16a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_query_chunks_link',
    sa.Column('cached_query_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cached_query_id'], ['cached_queries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cached_query_id', 'chunk_id')
    )
    op.drop_column('cached_queries', 'response_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_queries', sa.Column('response_sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('cached_query_chunks_link')
    # ### end Alembic commands ###
