"""Add cached_queries table for semantic caching

Revision ID: e40291de16a1
Revises: 4413860a671e
Create Date: 2025-11-10 11:43:37.650436

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e40291de16a1'
down_revision: Union[str, Sequence[str], None] = '4413860a671e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('response_answer', sa.String(), nullable=False),
    sa.Column('response_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_cached_queries_embedding',
        'cached_queries',
        ['question_embedding'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_ops={'question_embedding': 'vector_cosine_ops'}
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_queries')
    # ### end Alembic commands ###
